# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-09-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='places',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
