# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-09-19 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='places',
        ),
    ]
