# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-09-19 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='creator',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
    ]
